version: '3'
services:
  react-app:
    image: project_client
    ports:
      - "3000:3000"

  api-app:
    image: project_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV = development
      - PORT = 5000
      - MONGODB_LINK = "mongodb+srv://n33dl34dm1n:ma4ng31pomme@cluster0.ydg15.mongodb.net/NWSOctoberProjects?retryWrites=true&w=majority"
      - JWT_SECRET = "n0rm4nd13"
    restart: always
