version: '3'
services:
  react-app:
    image: project_client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  api-app:
    image: project_backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    environment:
      - NODE_ENV = production
      - PORT = 5000
      - MONGODB_LINK = "mongodb+srv://n33dl34dm1n:ma4ng31pomme@cluster0.ydg15.mongodb.net/NWSOctoberProjects?retryWrites=true&w=majority"
      - JWT_SECRET = "n0rm4nd13"
    restart: always
networks:
  mern-app:
    driver: bridge
