version: "3"
services:
  react-app:
    image: project_client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  api-app:
    image: project_backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    restart: always
networks:
  mern-app:
    driver: bridge
