name: Deploy

on:
  push:
    branches:
      - release

jobs:
  test code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd server && npm i
      - run: npm run test

  Merge release into master:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: everlytic/branch-merge@1.1.2
          with:
            github_token: ${{ github.token }}
            source_ref: "release"
            target_branch: "master"
            commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"

  Connect to server SSH:
      runs-on: ubuntu-latest
      steps:
        - run: |
            mkdir -p ~/.ssh
            ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
        - uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

        - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd /home/debian/projetNWSOctobre && ansible-playbook deployapp_playbook.yml"
