name: Deploy to production

on:
  push:
    branches:
      - release

jobs:
  Test_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd server && npm i
      - run: npm run test

  Merge_release_into_master:
      runs-on: ubuntu-latest
      needs: Test_code
      steps:
        - uses: actions/checkout@v2
        - uses: everlytic/branch-merge@1.1.2
          with:
            github_token: ${{ github.token }}
            source_ref: "release"
            target_branch: "master"
            commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"

  Check_docker_on_server:
      runs-on: ubuntu-latest
      needs: Merge_release_into_master
      steps:
        - run: |
            mkdir -p ~/.ssh
            ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
        - uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

        - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd /home/debian/ansible && ansible-playbook handle_docker_install_or_update.yaml"
